FROM python:3.12-slim
RUN apt-get update && apt-get install -y build-essential
WORKDIR /app
ADD ui/requirements.txt /app/
RUN pip3 install -r requirements.txt

ADD ui/faucet.py /app/
ADD ui/pow.py /app/

ENV POW=1000

CMD ["streamlit", "run", "faucet.py"]